### ISSUE TITLE
Consider using sandboxing as defense in depth

### ISSUE THREAD

**Issue by dlight** [dtolnay/watt#7]
Rustc has a number of [known soundness bugs](https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+label%3A%22I-unsound+%F0%9F%92%A5%22). What about running wasm code on a lightweight sandbox like [gaol](https://github.com/servo/gaol) or [rusty-sandbox](https://github.com/myfreeweb/rusty-sandbox) as a best-effort attempt to provide defense in depth?

**Comment by dtolnay** [comment]
Thanks for the idea! I am not interested in pursuing this in Watt, but it would be worth bringing up again if we eventually go for Wasm-based proc macros built into rustc.
